# Generated by Django 2.1.5 on 2019-02-05 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='submition_date',
            new_name='submission_date',
        ),
    ]
