# Generated by Django 2.1.5 on 2019-02-05 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0002_auto_20190205_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='vaccination',
            new_name='vaccinations',
        ),
    ]
